import Head from 'next/head';

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>Welcome to my Next.js app!</h1>
      </main>
    </div>
  );
}
